
package nezet;

import java.awt.Button;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author weimper.g.zsombor
 */
public class GuiNezet extends javax.swing.JFrame {

    /**
     * Creates new form GuiNezet
     */
    public GuiNezet() {
        initComponents();
    }

    public void megjelenit(String uzenet){
        txa_leiras.setText(uzenet);
    }
    
    public int bekeres() {
        //ButtonModel[] btns = new ButtonModel[3];
        /*int ind = 0;
        
        while(ind < btg_ladak.getButtonCount()){
            ButtonModel gomb = btg_ladak.getSelection();
            
        }*/
        int v = -1;
        if(rbt_aranylada.isSelected()) v = 0;
        else if(rbt_ezustlada.isSelected()) v = 1;
        else if(rbt_bronzlada.isSelected()) v = 2;
        return v;
    }
    
    public void figyelmeztet(String uzenet){
        JOptionPane.showMessageDialog(null, uzenet);
        
    }

    public JButton getBtn_valasztas() {
        return btn_valasztas;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_ladak = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_leiras = new javax.swing.JTextArea();
        rbt_aranylada = new javax.swing.JRadioButton();
        rbt_ezustlada = new javax.swing.JRadioButton();
        rbt_bronzlada = new javax.swing.JRadioButton();
        btn_valasztas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txa_leiras.setColumns(20);
        txa_leiras.setRows(5);
        jScrollPane1.setViewportView(txa_leiras);

        btg_ladak.add(rbt_aranylada);
        rbt_aranylada.setText("Aranyláda");

        btg_ladak.add(rbt_ezustlada);
        rbt_ezustlada.setText("Ezüstláda");

        btg_ladak.add(rbt_bronzlada);
        rbt_bronzlada.setText("Bronzláda");

        btn_valasztas.setText("Választ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbt_ezustlada)
                            .addComponent(rbt_aranylada))
                        .addGap(28, 317, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbt_bronzlada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_valasztas)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(rbt_aranylada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbt_ezustlada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_bronzlada)
                    .addComponent(btn_valasztas))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_ladak;
    private javax.swing.JButton btn_valasztas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbt_aranylada;
    private javax.swing.JRadioButton rbt_bronzlada;
    private javax.swing.JRadioButton rbt_ezustlada;
    private javax.swing.JTextArea txa_leiras;
    // End of variables declaration//GEN-END:variables
}
